language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.m2
install: true #Override default build step for maven (bad Travis!)
script:
  - mvn clean install -Dgpg.skip=true
after_success:
  - mvn clean test jacoco:report coveralls:report -Dgpg.skip=true
notifications:
  email:
    recipients:
      - jmsotuyo@monits.com
