language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.m2
script: "mvn clean install"
after_success:
  - mvn clean test jacoco:report coveralls:report
notifications:
  email:
    recipients:
      - jmsotuyo@monits.com
